/* ============================================================
   BANCO DE QUESTÕES — Educação Digital
   Turma: 3º Ano A (Ensino Médio Regular)
   60 questões (20 fáceis, 20 médias, 20 difíceis) — tipo "mc"
   Conteúdo: uso ético da IA, mitos e verdades, IH x IA,
   arquitetura (LLM/rede neural/aprendizado de máquina),
   processo de aprendizado de máquina, tokens e limites.
   ============================================================ */
const BANCO_3A = [

/* ---------------------------------------------------------- NÍVEL 1 (fácil) */
{ id:"b1-01", nivel:1, tipo:"mc", leitura:14, decay:25,
  enunciado:"Quando alguém recebe um trabalho pronto de uma IA e o entrega sem ter pensado sobre o conteúdo, o que essa pessoa fez?",
  alternativas:[
    {t:"Terceirizou o aprendizado, deixando a máquina pensar no lugar dela.", ok:true},
    {t:"Estudou o assunto com mais profundidade do que faria sozinha.", ok:false},
    {t:"Usou a IA apenas para revisar a ortografia de um texto próprio.", ok:false},
    {t:"Fez uma pesquisa em fontes bibliográficas confiáveis.", ok:false}],
  explicacao:"Receber o resultado pronto, sem produzir o raciocínio, é abrir mão do próprio aprendizado." },
{ id:"b1-02", nivel:1, tipo:"mc", leitura:12, decay:25,
  enunciado:"Por que um professor pode desconfiar de um texto 'perfeito demais' entregue por um aluno?",
  alternativas:[
    {t:"Porque pode faltar o estilo pessoal de escrita que o professor já reconhece naquele aluno.", ok:true},
    {t:"Porque textos perfeitos são sempre proibidos na escola.", ok:false},
    {t:"Porque um texto sem erros nunca pode ser verdadeiro.", ok:false},
    {t:"Porque professores não avaliam a qualidade da escrita.", ok:false}],
  explicacao:"A ausência da 'marca pessoal' de quem escreve costuma denunciar um texto gerado por IA." },
{ id:"b1-03", nivel:1, tipo:"mc", leitura:12, decay:22,
  enunciado:"A Inteligência Artificial tem consciência de si mesma, como um ser humano?",
  alternativas:[
    {t:"Não — ela processa dados e padrões, mas não possui consciência.", ok:true},
    {t:"Sim — toda IA moderna já desenvolveu consciência própria.", ok:false},
    {t:"Sim — é por isso que ela consegue sentir emoções reais.", ok:false},
    {t:"Sim, mas apenas os modelos mais antigos tinham consciência.", ok:false}],
  explicacao:"Consciência e sentimentos continuam sendo exclusivos da ficção quando se fala de IA real." },
{ id:"b1-04", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"Por que uma Inteligência Artificial pode reproduzir preconceitos em suas respostas?",
  alternativas:[
    {t:"Porque ela aprende com dados, e dados enviesados geram respostas enviesadas.", ok:true},
    {t:"Porque os programadores inserem preconceitos de propósito, sempre.", ok:false},
    {t:"Porque a internet fica congestionada durante o uso da IA.", ok:false},
    {t:"Isso nunca acontece: a IA é sempre neutra.", ok:false}],
  explicacao:"A resposta da IA reflete diretamente a qualidade e a diversidade dos dados usados no treino." },
{ id:"b1-05", nivel:1, tipo:"mc", leitura:12, decay:20,
  enunciado:"O que quer dizer a sigla LLM, usada para descrever modelos como os que geram texto em chatbots?",
  alternativas:[
    {t:"Large Language Model — Grande Modelo de Linguagem.", ok:true},
    {t:"Long Live Machine — Máquina de Longa Duração.", ok:false},
    {t:"Linked Learning Method — Método de Aprendizado Conectado.", ok:false},
    {t:"Light Language Memory — Memória Leve de Linguagem.", ok:false}],
  explicacao:"É o programa treinado com milhões de textos, capaz de entender e gerar linguagem humana." },
{ id:"b1-06", nivel:1, tipo:"mc", leitura:12, decay:20,
  enunciado:"Em que a estrutura de uma rede neural artificial se inspira?",
  alternativas:[
    {t:"No funcionamento do cérebro humano.", ok:true},
    {t:"No sistema de fibra óptica da internet.", ok:false},
    {t:"Na estrutura de uma planilha eletrônica.", ok:false},
    {t:"No funcionamento de um controle remoto.", ok:false}],
  explicacao:"A rede neural ajuda a IA a processar informações complexas, como imagens, sons e palavras." },
{ id:"b1-07", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"O que é o Aprendizado de Máquina, de forma simples?",
  alternativas:[
    {t:"A técnica que permite à IA melhorar sozinha, analisando exemplos e ajustando as próprias respostas.", ok:true},
    {t:"Um programa que só serve para jogos eletrônicos.", ok:false},
    {t:"Um curso presencial obrigatório de informática.", ok:false},
    {t:"O nome do fabricante de um computador.", ok:false}],
  explicacao:"Assim como uma criança aprende a reconhecer gatos vendo muitas fotos, a IA aprende por exemplos." },
{ id:"b1-08", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"Qual é a primeira etapa do processo de Aprendizado de Máquina?",
  alternativas:[
    {t:"A coleta de dados relevantes e variados.", ok:true},
    {t:"O ajuste final dos parâmetros do modelo.", ok:false},
    {t:"A entrega da resposta pronta ao usuário.", ok:false},
    {t:"A geração de uma imagem artística.", ok:false}],
  explicacao:"Sem dados coletados primeiro, não há o que o algoritmo possa analisar." },
{ id:"b1-09", nivel:1, tipo:"mc", leitura:12, decay:20,
  enunciado:"O que é um token no contexto de treinamento de modelos de linguagem?",
  alternativas:[
    {t:"A unidade básica de texto processada pelo modelo — pode ser uma palavra, parte dela ou um caractere.", ok:true},
    {t:"Uma senha secreta usada para acessar a IA.", ok:false},
    {t:"O nome de cada pergunta feita por um usuário.", ok:false},
    {t:"Um tipo de imagem usada no treinamento de redes neurais.", ok:false}],
  explicacao:"É essa unidade que serve de medida para o volume de dados usado no treinamento de um LLM." },
{ id:"b1-10", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"Chatbots simples e assistentes de voz são inteligentes de que jeito?",
  alternativas:[
    {t:"Apenas dentro de um contexto limitado, seguindo roteiros programados.", ok:true},
    {t:"São capazes de resolver absolutamente qualquer situação.", ok:false},
    {t:"Aprendem qualquer assunto sozinhos, sem depender de programação.", ok:false},
    {t:"Têm consciência plena das conversas que realizam.", ok:false}],
  explicacao:"Fora do contexto para o qual foram programados, esses sistemas costumam falhar." },
{ id:"b1-11", nivel:1, tipo:"mc", leitura:12, decay:20,
  enunciado:"De que forma a Inteligência Humana costuma aprender?",
  alternativas:[
    {t:"Por experiência, emoção e interação social — observando, errando e debatendo.", ok:true},
    {t:"Exclusivamente analisando grandes bancos de dados numéricos.", ok:false},
    {t:"Da mesma forma exata que uma Inteligência Artificial.", ok:false},
    {t:"Somente por meio de manuais técnicos escritos.", ok:false}],
  explicacao:"A aprendizagem humana envolve intuição e vivência — algo que a IA não experimenta." },
{ id:"b1-12", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"Que tipo de modelo de IA é treinado com foco em uma área específica, como direito ou medicina?",
  alternativas:[
    {t:"Modelo especializado.", ok:true},
    {t:"Modelo genérico.", ok:false},
    {t:"Modelo multimídia.", ok:false},
    {t:"Modelo de rede social.", ok:false}],
  explicacao:"Esse tipo de modelo busca informações precisas dentro de um setor específico do conhecimento." },
{ id:"b1-13", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"Qual tipo de modelo de IA serve para criar imagens, vídeos ou músicas?",
  alternativas:[
    {t:"Modelo de geração de conteúdo visual ou multimídia.", ok:true},
    {t:"Modelo de análise de dados financeiros.", ok:false},
    {t:"Modelo especializado em saúde.", ok:false},
    {t:"Modelo genérico de texto.", ok:false}],
  explicacao:"Esse tipo de modelo é aplicado em publicidade, entretenimento e produção artística." },
{ id:"b1-14", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"Uma empresa quer analisar milhões de transações para descobrir padrões suspeitos. Que tipo de modelo de IA atende melhor essa necessidade?",
  alternativas:[
    {t:"Modelo de compreensão e análise de dados.", ok:true},
    {t:"Modelo de geração multimídia.", ok:false},
    {t:"Modelo genérico de conversação.", ok:false},
    {t:"Modelo especializado em direito.", ok:false}],
  explicacao:"Esse modelo interpreta grandes volumes de dados, identifica tendências e detecta fraudes." },
{ id:"b1-15", nivel:1, tipo:"mc", leitura:12, decay:20,
  enunciado:"O que caracteriza um uso ético da IA em uma pesquisa escolar?",
  alternativas:[
    {t:"Usar a IA para entender o tema, verificar as informações e escrever com as próprias palavras.", ok:true},
    {t:"Copiar a resposta da IA sem revisar nem verificar nada.", ok:false},
    {t:"Confiar automaticamente em qualquer informação bem redigida.", ok:false},
    {t:"Nunca mencionar que a IA foi consultada durante a pesquisa.", ok:false}],
  explicacao:"O uso ético mantém a IA como apoio, mas preserva a verificação e a autoria da pessoa." },
{ id:"b1-16", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"Quais desafios o uso da Inteligência Artificial levanta para a sociedade, segundo o material estudado?",
  alternativas:[
    {t:"Privacidade individual, transformação do mercado de trabalho e ética nas interações digitais.", ok:true},
    {t:"Apenas o custo alto de acesso à internet.", ok:false},
    {t:"Apenas a demora no carregamento de páginas web.", ok:false},
    {t:"Nenhum desafio relevante é mencionado.", ok:false}],
  explicacao:"São questões que precisam ser enfrentadas de forma consciente junto com os benefícios da IA." },
{ id:"b1-17", nivel:1, tipo:"mc", leitura:12, decay:20,
  enunciado:"Qual é aproximadamente a escala de tokens usada para treinar as IAs mais populares do mundo?",
  alternativas:[
    {t:"Entre 100 e 300 bilhões de tokens.", ok:true},
    {t:"Cerca de 300 tokens.", ok:false},
    {t:"Cerca de 50 mil tokens.", ok:false},
    {t:"Um número impossível de medir.", ok:false}],
  explicacao:"O treinamento de grandes modelos de linguagem envolve uma escala de bilhões de tokens." },
{ id:"b1-18", nivel:1, tipo:"mc", leitura:12, decay:20,
  enunciado:"O que tende a acontecer se os dados usados para treinar uma IA forem falhos ou incompletos?",
  alternativas:[
    {t:"As respostas da IA podem ficar imprecisas, repetindo esses mesmos problemas.", ok:true},
    {t:"As respostas ficam automaticamente perfeitas.", ok:false},
    {t:"O sistema deixa de funcionar por completo, sempre.", ok:false},
    {t:"Nada muda: a qualidade dos dados não influencia em nada.", ok:false}],
  explicacao:"A confiabilidade da resposta está diretamente ligada à qualidade dos dados de treinamento." },
{ id:"b1-19", nivel:1, tipo:"mc", leitura:12, decay:20,
  enunciado:"Segundo o material, a IA vai eliminar por completo o trabalho humano no futuro próximo?",
  alternativas:[
    {t:"Não — ela substitui tarefas repetitivas, mas também cria novas funções, exigindo adaptação.", ok:true},
    {t:"Sim — em breve não existirá mais nenhum tipo de emprego humano.", ok:false},
    {t:"Sim — isso já aconteceu por completo.", ok:false},
    {t:"O material não aborda esse assunto.", ok:false}],
  explicacao:"O mercado de trabalho muda e se adapta; a IA não elimina totalmente o trabalho humano." },
{ id:"b1-20", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"Quando uma IA identifica que uma mensagem parece triste e responde com uma frase de apoio, ela está sentindo empatia de verdade?",
  alternativas:[
    {t:"Não — ela reconhece padrões em palavras, como um detector, sem sentir nada de fato.", ok:true},
    {t:"Sim — toda IA sente as emoções que identifica no texto.", ok:false},
    {t:"Sim, mas apenas se a mensagem tiver mais de 100 palavras.", ok:false},
    {t:"A IA nunca consegue identificar nenhum tom emocional em um texto.", ok:false}],
  explicacao:"Perceber um padrão não é o mesmo que sentir — a IA simula, mas não vivencia a emoção." },

/* ---------------------------------------------------------- NÍVEL 2 (médio) */
{ id:"b2-01", nivel:2, tipo:"mc", leitura:22, decay:35,
  texto:"Dois colegas resolveram testar uma ferramenta de IA a fundo: pediram poemas, redações e piadas, e o resultado sempre chegava rápido e tecnicamente correto.",
  enunciado:"Que dúvida importante essa experiência levanta sobre o uso da IA nos estudos?",
  alternativas:[
    {t:"Se estavam de fato aprendendo, ou apenas recebendo resultados prontos sem esforço próprio.", ok:true},
    {t:"Se a ferramenta cobrava alguma taxa para gerar tantos textos.", ok:false},
    {t:"Se o navegador usado era compatível com a ferramenta.", ok:false},
    {t:"Se a IA conseguiria repetir a resposta com as mesmas palavras.", ok:false}],
  explicacao:"Qualidade técnica do texto não garante que houve aprendizagem por parte de quem pediu." },
{ id:"b2-02", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Qual das situações abaixo representa um uso coerente e responsável da Inteligência Artificial em um trabalho escolar?",
  alternativas:[
    {t:"Pedir ideias e exemplos à IA, verificar as informações e citar de onde vieram.", ok:true},
    {t:"Entregar como próprio um texto totalmente gerado pela IA, sem revisão.", ok:false},
    {t:"Aceitar qualquer resposta só porque parece bem escrita.", ok:false},
    {t:"Pedir à IA para inventar uma fonte quando não encontra uma real.", ok:false}],
  explicacao:"O apoio da IA é válido quando a verificação e a autoria continuam sendo do estudante." },
{ id:"b2-03", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Por que a afirmação 'a IA nunca erra, então é mais confiável que qualquer pessoa' é considerada um mito?",
  alternativas:[
    {t:"Porque ela aprende com dados que podem conter erros ou vieses, exigindo supervisão humana constante.", ok:true},
    {t:"Porque, na prática, a IA nunca comete nenhum tipo de erro.", ok:false},
    {t:"Porque pessoas são sempre mais rápidas em qualquer tarefa do que a IA.", ok:false},
    {t:"Porque a IA só funciona corretamente quando está sem conexão à internet.", ok:false}],
  explicacao:"Erros e vieses presentes nos dados de treinamento se refletem diretamente nas respostas." },
{ id:"b2-04", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Qual frase resume melhor a diferença entre a IA dos filmes de ficção e a IA que existe de fato hoje?",
  alternativas:[
    {t:"A IA real é uma ferramenta poderosa que processa dados e padrões; sentimentos e consciência seguem sendo ficção.", ok:true},
    {t:"A IA real já sente e decide de forma totalmente independente, como nos filmes.", ok:false},
    {t:"A IA real e a de ficção são exatamente iguais, mudando apenas a velocidade.", ok:false},
    {t:"A IA de ficção é sempre tecnicamente mais fraca que a real.", ok:false}],
  explicacao:"O poder computacional é real; a consciência e as emoções continuam pertencendo à ficção." },
{ id:"b2-05", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Uma característica descrita é: 'resolve um problema de um jeito nunca tentado antes, unindo experiências, cultura e intuição'. A que tipo de inteligência isso pertence?",
  alternativas:[
    {t:"Inteligência Humana (IH).", ok:true},
    {t:"Inteligência Artificial (IA).", ok:false},
    {t:"Nenhuma das duas.", ok:false},
    {t:"Apenas modelos de IA multimídia.", ok:false}],
  explicacao:"Combinar vivência pessoal e intuição é uma marca da criatividade humana genuína." },
{ id:"b2-06", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Uma característica descrita é: 'analisa milhares de exemplos por segundo à procura de padrões'. A que tipo de inteligência isso pertence?",
  alternativas:[
    {t:"Inteligência Artificial (IA).", ok:true},
    {t:"Inteligência Humana (IH).", ok:false},
    {t:"Nenhuma das duas.", ok:false},
    {t:"Apenas a inteligência emocional humana.", ok:false}],
  explicacao:"A velocidade de processamento em larga escala é uma força típica da máquina." },
{ id:"b2-07", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Por que uma IA depende de reprogramação ou de novos dados para mudar sua forma de responder, diferente de uma pessoa?",
  alternativas:[
    {t:"Porque ela só é adaptável dentro dos limites do que já foi ensinado a ela.", ok:true},
    {t:"Porque ela se recusa deliberadamente a aprender qualquer coisa nova.", ok:false},
    {t:"Isso não é verdade: a IA se atualiza sozinha, sem depender de nada externo.", ok:false},
    {t:"Porque ela tem memória ilimitada e nunca precisa de ajustes.", ok:false}],
  explicacao:"A flexibilidade humana vem da vivência; a IA só muda dentro do que os dados permitem." },
{ id:"b2-08", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Um consultório jurídico quer uma ferramenta de IA que consulte leis e jurisprudências com precisão. Qual tipo de modelo é mais indicado?",
  alternativas:[
    {t:"Modelo especializado, treinado com foco na área jurídica.", ok:true},
    {t:"Modelo de geração de conteúdo multimídia.", ok:false},
    {t:"Modelo genérico de conversação.", ok:false},
    {t:"Modelo de análise de dados financeiros.", ok:false}],
  explicacao:"Modelos especializados focam em um setor para entregar respostas tecnicamente precisas." },
{ id:"b2-09", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Depois de analisar milhares de imagens em busca de padrões, qual é a próxima etapa do Aprendizado de Máquina?",
  alternativas:[
    {t:"Comparar o resultado obtido com o esperado e ajustar os parâmetros internos do modelo.", ok:true},
    {t:"Apagar imediatamente todas as imagens usadas.", ok:false},
    {t:"Encerrar o processo, já que a coleta é a única etapa necessária.", ok:false},
    {t:"Enviar as imagens para impressão em papel.", ok:false}],
  explicacao:"O ciclo do aprendizado é coleta → análise de padrões → ajuste de parâmetros, repetido várias vezes." },
{ id:"b2-10", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Por que 'quanto mais dados, melhor' não é uma regra totalmente livre de custos?",
  alternativas:[
    {t:"Porque um volume maior de dados aumenta o tempo e o custo computacional do treinamento.", ok:true},
    {t:"Porque a IA apaga os dados antigos assim que recebe dados novos.", ok:false},
    {t:"Porque dados em excesso impedem qualquer reconhecimento de padrão.", ok:false},
    {t:"Porque não existe limite algum para o volume de dados processado.", ok:false}],
  explicacao:"Mais dados relevantes ajudam no aprendizado, mas custam tempo e recursos computacionais." },
{ id:"b2-11", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Uma produtora audiovisual precisa gerar trilhas sonoras originais para um curta-metragem. Qual tipo de modelo de IA é mais indicado?",
  alternativas:[
    {t:"Modelo de geração de conteúdo visual ou multimídia.", ok:true},
    {t:"Modelo especializado em medicina.", ok:false},
    {t:"Modelo de compreensão e análise de dados.", ok:false},
    {t:"Modelo genérico apenas de texto.", ok:false}],
  explicacao:"Criação de músicas, imagens e vídeos é a função do modelo de geração multimídia." },
{ id:"b2-12", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"O que está por trás da capacidade de um chatbot manter uma conversa fluente em português?",
  alternativas:[
    {t:"Um LLM (Modelo de Linguagem), treinado para compreender e produzir texto.", ok:true},
    {t:"Apenas uma lista fixa de frases digitadas manualmente por uma pessoa.", ok:false},
    {t:"Um tradutor automático simples, sem relação com modelos de linguagem.", ok:false},
    {t:"Somente a rede neural, sem nenhum modelo de linguagem envolvido.", ok:false}],
  explicacao:"O modelo de linguagem é a parte responsável por entender e gerar o texto da conversa." },
{ id:"b2-13", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Qual é a conclusão do capítulo sobre a relação entre Inteligência Humana e Inteligência Artificial?",
  alternativas:[
    {t:"O melhor caminho é combinar a eficiência da IA com a profundidade e a empatia humanas.", ok:true},
    {t:"A IA vai superar completamente a inteligência humana em pouco tempo.", ok:false},
    {t:"A IA deve ser proibida nas escolas por atrapalhar o raciocínio.", ok:false},
    {t:"A Inteligência Humana perdeu toda a sua relevância.", ok:false}],
  explicacao:"A proposta é usar as duas juntas, cada uma na função em que é mais forte." },
{ id:"b2-14", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Por que 'mudar de opinião após ouvir um bom argumento em um debate' é considerado um exemplo de Inteligência Humana, e não Artificial?",
  alternativas:[
    {t:"Porque mostra flexibilidade real, construída pela reflexão e pela experiência da própria pessoa.", ok:true},
    {t:"Porque a IA jamais recebe qualquer tipo de argumento.", ok:false},
    {t:"Porque debater é uma atividade restrita apenas a máquinas.", ok:false},
    {t:"Porque essa situação não tem relação alguma com inteligência.", ok:false}],
  explicacao:"A IA só muda de resposta com reprogramação ou novos dados; a pessoa muda por reflexão própria." },
{ id:"b2-15", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Um sistema identifica uma expressão de tristeza em uma foto e responde com uma mensagem de apoio programada. Isso prova que a IA sentiu empatia genuína?",
  alternativas:[
    {t:"Não — é uma simulação de resposta emocional, sem sentimento real por trás.", ok:true},
    {t:"Sim — qualquer IA que reconhece expressões sente emoções reais.", ok:false},
    {t:"Sim — reconhecer uma expressão é idêntico a sentir a emoção.", ok:false},
    {t:"É impossível uma IA reconhecer expressões faciais.", ok:false}],
  explicacao:"A IA identifica padrões visuais e responde de forma programada — não há emoção envolvida." },
{ id:"b2-16", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Qual é a principal diferença entre como a IH e a IA lidam com problemas complexos?",
  alternativas:[
    {t:"A IH considera dados, emoções e intuição; a IA segue regras e padrões dentro dos limites dos dados que recebeu.", ok:true},
    {t:"Ambas resolvem problemas exatamente da mesma maneira.", ok:false},
    {t:"A IA sempre demora mais tempo do que a IH para resolver qualquer problema.", ok:false},
    {t:"A IH também depende só de regras matemáticas fixas.", ok:false}],
  explicacao:"A flexibilidade da IH vem da bagagem cultural e emocional; a IA é limitada aos dados recebidos." },
{ id:"b2-17", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Um texto gerado por IA pode estar tecnicamente correto e, ainda assim, representar um problema de aprendizagem. Por quê?",
  alternativas:[
    {t:"Porque a correção técnica não garante que a pessoa realmente compreendeu ou produziu aquele conteúdo.", ok:true},
    {t:"Porque textos corretos são proibidos em atividades escolares.", ok:false},
    {t:"Porque a IA nunca gera textos tecnicamente corretos.", ok:false},
    {t:"Porque somente textos com erros têm valor pedagógico.", ok:false}],
  explicacao:"O problema não é a qualidade do texto — é a ausência do processo de aprendizagem." },
{ id:"b2-18", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Como o Aprendizado de Máquina consegue reconhecer um objeto em uma imagem nunca vista antes?",
  alternativas:[
    {t:"Analisando muitos exemplos, identificando padrões comuns e generalizando esse aprendizado para casos novos.", ok:true},
    {t:"Memorizando individualmente cada imagem já vista, sem generalizar nada.", ok:false},
    {t:"Perguntando a uma pessoa antes de cada resposta.", ok:false},
    {t:"Usando sempre uma única imagem de referência fixa.", ok:false}],
  explicacao:"É o processo de generalização a partir de muitos exemplos que permite reconhecer casos inéditos." },
{ id:"b2-19", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Por que verificar uma informação em pelo menos duas fontes confiáveis é recomendado ao usar respostas de IA?",
  alternativas:[
    {t:"Porque a IA pode gerar respostas com dados incompletos, desatualizados ou tendenciosos.", ok:true},
    {t:"Porque a IA sempre erra de propósito para testar quem está usando.", ok:false},
    {t:"Porque duas fontes sempre concordam automaticamente entre si.", ok:false},
    {t:"Porque isso só é exigido em trabalhos universitários.", ok:false}],
  explicacao:"Checar fontes reduz o risco de espalhar informações falsas ou enviesadas produzidas pela IA." },
{ id:"b2-20", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Qual é a função de um modelo de IA do tipo genérico?",
  alternativas:[
    {t:"Entender e gerar textos variados, servindo a chatbots, tradutores e apoio à escrita.", ok:true},
    {t:"Funcionar exclusivamente dentro de hospitais.", ok:false},
    {t:"Gerar apenas imagens publicitárias.", ok:false},
    {t:"Detectar fraudes financeiras em tempo real.", ok:false}],
  explicacao:"O modelo genérico é versátil, aplicado em educação, atendimento e criação de conteúdo." },

/* ---------------------------------------------------------- NÍVEL 3 (difícil) */
{ id:"b3-01", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Se o aprendizado de máquina é construído por tentativa, erro e ajuste, o que isso implica sobre confiar cegamente em qualquer resposta gerada por IA?",
  alternativas:[
    {t:"Que não se deve confiar sem checagem: mesmo generalizando bem, o modelo pode falhar diante de casos fora do padrão aprendido.", ok:true},
    {t:"Que toda resposta de uma IA está sempre correta, sem exceções.", ok:false},
    {t:"Que a tentativa e erro só ocorre uma vez, no começo do treinamento.", ok:false},
    {t:"Que a IA para de errar assim que o treinamento termina.", ok:false}],
  explicacao:"O processo de tentativa e erro mostra que o modelo pode falhar diante de situações atípicas." },
{ id:"b3-02", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Um estudante usa a IA para gerar ideias, mas reescreve tudo com as próprias palavras, verifica as fontes e informa que consultou a ferramenta. Por que essa conduta continua sendo ética, mesmo usando IA amplamente?",
  alternativas:[
    {t:"Porque a autoria, a verificação e a transparência continuam sendo dele — a IA serviu de apoio, não de substituição.", ok:true},
    {t:"Porque usar IA de qualquer forma já é sempre antiético, independentemente do cuidado.", ok:false},
    {t:"Porque avisar que usou a IA torna qualquer conduta aceitável, mesmo sem verificação alguma.", ok:false},
    {t:"Porque reescrever com outras palavras já garante 100% de precisão nas informações.", ok:false}],
  explicacao:"O uso ético preserva a responsabilidade humana sobre a verificação e a autoria do conteúdo." },
{ id:"b3-03", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que dizer 'a IA vai roubar todos os empregos e nos tornar obsoletos' é tratado como um mito, mesmo sabendo que a IA realmente substitui tarefas repetitivas?",
  alternativas:[
    {t:"Porque a substituição de tarefas repetitivas ocorre junto com a criação de novas funções, exigindo adaptação em vez de eliminação total.", ok:true},
    {t:"Porque a IA nunca substitui absolutamente nenhuma tarefa.", ok:false},
    {t:"Porque tarefas repetitivas deixaram de existir desde a criação da IA.", ok:false},
    {t:"Porque tecnologia nunca provoca mudanças no mercado de trabalho.", ok:false}],
  explicacao:"O mito está no exagero da eliminação total; a realidade é transformação e necessidade de adaptação." },
{ id:"b3-04", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que afirmar que uma IA 'decide' com base em uma única métrica objetiva costuma ser uma simplificação equivocada?",
  alternativas:[
    {t:"Porque as respostas de uma IA envolvem padrões aprendidos e ponderações internas complexas, não apenas uma variável isolada.", ok:true},
    {t:"Porque a IA nunca utiliza nenhum tipo de dado numérico em seus processos.", ok:false},
    {t:"Porque só existe uma única forma possível de qualquer IA funcionar.", ok:false},
    {t:"Porque métricas objetivas são proibidas em sistemas de Inteligência Artificial.", ok:false}],
  explicacao:"O 'raciocínio' de um modelo combina múltiplos padrões — não se resume a uma única variável simples." },
{ id:"b3-05", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Um sistema de recrutamento por IA é treinado majoritariamente com currículos aprovados de um único perfil de candidatos. Qual risco isso cria?",
  alternativas:[
    {t:"O modelo pode reproduzir o mesmo viés presente nos dados, prejudicando candidatos fora daquele perfil.", ok:true},
    {t:"Nenhum risco — sistemas de IA sempre avaliam todos os perfis de forma igualmente justa.", ok:false},
    {t:"O sistema apaga automaticamente todos os dados anteriores.", ok:false},
    {t:"O risco só existiria se o modelo fosse do tipo multimídia.", ok:false}],
  explicacao:"Dados de treinamento pouco diversos tendem a gerar respostas enviesadas contra quem está fora da amostra original." },
{ id:"b3-06", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que a criatividade humana é descrita como algo que une experiência, cultura e intuição, enquanto a IA 'combina elementos já existentes sem intenção própria'?",
  alternativas:[
    {t:"Porque a IA gera conteúdo a partir de padrões aprendidos, sem propósito ou vivência pessoal por trás da escolha.", ok:true},
    {t:"Porque a IA nunca combina elementos de forma alguma.", ok:false},
    {t:"Porque a criatividade humana também segue regras fixas e programadas.", ok:false},
    {t:"Porque essa diferença é apenas uma opinião, sem fundamento no capítulo.", ok:false}],
  explicacao:"Intenção, cultura e vivência pessoal são exclusivamente humanas no processo criativo." },
{ id:"b3-07", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Um modelo de IA passa a responder de forma diferente a uma mesma pergunta, meses depois de receber um novo lote de dados de treinamento. O que isso demonstra?",
  alternativas:[
    {t:"Que a adaptação da IA depende de reprogramação ou de novos dados, e não de uma reflexão interna própria.", ok:true},
    {t:"Que a IA desenvolveu livre-arbítrio e decidiu mudar sozinha.", ok:false},
    {t:"Que o sistema está com defeito e precisa ser desligado.", ok:false},
    {t:"Que toda IA muda de resposta aleatoriamente, sem motivo algum.", ok:false}],
  explicacao:"A mudança vem de um fator externo (dados/ajustes), diferente da mudança de opinião humana." },
{ id:"b3-08", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que o capítulo defende combinar IH e IA em vez de escolher apenas uma delas?",
  alternativas:[
    {t:"Porque a IA contribui com velocidade e escala de processamento, e a IH com julgamento ético, criatividade e empatia — cada uma cobre a limitação da outra.", ok:true},
    {t:"Porque a IA sempre erra e precisa ser corrigida por humanos o tempo todo, sem exceção.", ok:false},
    {t:"Porque a IH é sempre mais rápida que a IA em qualquer cálculo numérico.", ok:false},
    {t:"Porque não existe nenhuma diferença real entre as duas.", ok:false}],
  explicacao:"A força de uma cobre exatamente a fraqueza da outra: velocidade computacional x profundidade humana." },
{ id:"b3-09", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que treinar um modelo com mais dados melhora a eficácia, mas ao mesmo tempo cria um dilema prático para quem o desenvolve?",
  alternativas:[
    {t:"Porque o ganho de qualidade custa mais tempo de processamento e mais recursos computacionais, criando um equilíbrio entre desempenho e custo.", ok:true},
    {t:"Porque mais dados sempre pioram a qualidade das respostas, sem exceção.", ok:false},
    {t:"Porque não existe custo algum associado ao volume de dados de treinamento.", ok:false},
    {t:"Porque dados extras são automaticamente descartados pelo próprio sistema.", ok:false}],
  explicacao:"Há um trade-off entre o volume de dados (que melhora o aprendizado) e o custo/tempo do treinamento." },
{ id:"b3-10", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Um colega afirma: 'se a resposta da IA parece bem escrita e segura, não preciso checar mais nada'. Qual é o principal risco dessa postura?",
  alternativas:[
    {t:"Uma escrita convincente não garante que a informação seja verdadeira — é justamente aí que mora o risco.", ok:true},
    {t:"Nenhum risco: texto bem escrito é sempre sinônimo de conteúdo correto.", ok:false},
    {t:"O risco é apenas estético, sem relação com a veracidade do conteúdo.", ok:false},
    {t:"Esse risco só existe em textos muito curtos, nunca em textos longos.", ok:false}],
  explicacao:"A fluência de um texto gerado por IA não tem relação direta com a exatidão factual do conteúdo." },
{ id:"b3-11", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que a escala de treinamento de uma IA é medida em tokens, e não em 'quantidade de livros' ou 'quantidade de textos'?",
  alternativas:[
    {t:"Porque o token é uma unidade mais granular de processamento, permitindo medir com precisão o volume real de linguagem processado.", ok:true},
    {t:"Porque contar textos inteiros é tecnicamente impossível para qualquer sistema.", ok:false},
    {t:"Porque token e texto são exatamente a mesma coisa, só com nomes diferentes.", ok:false},
    {t:"Porque essa é apenas uma escolha estética, sem função prática real.", ok:false}],
  explicacao:"Como um token pode ser uma palavra, parte dela ou um caractere, ele padroniza a medida de linguagem processada." },
{ id:"b3-12", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Uma empresa usa um modelo de IA genérico como assistente de atendimento, mas percebe que ele erra em dúvidas técnicas específicas de engenharia. Qual é a explicação mais provável?",
  alternativas:[
    {t:"Um modelo genérico não tem a mesma profundidade técnica de um modelo especializado naquela área específica.", ok:true},
    {t:"Modelos genéricos nunca cometem erros, então o problema deve estar na internet da empresa.", ok:false},
    {t:"Todo modelo de IA é sempre especializado em todas as áreas ao mesmo tempo.", ok:false},
    {t:"O erro só pode ter sido causado por um vírus no sistema.", ok:false}],
  explicacao:"Modelos genéricos são versáteis, mas modelos especializados oferecem precisão técnica dentro de uma área." },
{ id:"b3-13", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que a privacidade individual é considerada um dos grandes desafios trazidos pela Inteligência Artificial?",
  alternativas:[
    {t:"Porque muitos sistemas de IA processam grandes volumes de dados pessoais para funcionar, o que exige cuidado sobre como esses dados são usados e protegidos.", ok:true},
    {t:"Porque a IA nunca lida com nenhum tipo de dado pessoal.", ok:false},
    {t:"Porque privacidade é um tema exclusivo de jogos eletrônicos.", ok:false},
    {t:"Porque esse assunto não tem relação alguma com tecnologia.", ok:false}],
  explicacao:"O funcionamento de muitos sistemas de IA depende de dados — inclusive pessoais — o que exige regulação e cuidado ético." },
{ id:"b3-14", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Um algoritmo de recomendação, treinado com as interações de um grupo pequeno e pouco diverso de usuários, passa a sugerir cada vez menos variedade de conteúdo para todos. Que conceito explica esse efeito?",
  alternativas:[
    {t:"O aprendizado a partir de dados enviesados ou pouco diversos, que a IA reproduz e amplifica em suas respostas.", ok:true},
    {t:"A IA decidiu, por conta própria, restringir a diversidade por questões éticas.", ok:false},
    {t:"Algoritmos de recomendação nunca são treinados com dados de usuários reais.", ok:false},
    {t:"Esse efeito é tecnicamente impossível em qualquer sistema de IA.", ok:false}],
  explicacao:"Dados de treinamento pouco diversos tendem a se refletir — e até se intensificar — nas respostas geradas." },
{ id:"b3-15", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que afirmar que a IA 'não tem juízo de mérito' é central para entender seus limites éticos?",
  alternativas:[
    {t:"Porque, sem consciência própria, ela não avalia se uma resposta é moralmente certa ou errada — apenas devolve o que o aprendizado sugere.", ok:true},
    {t:"Porque juízo de mérito é um conceito que só existe em tribunais, sem relação com IA.", ok:false},
    {t:"Porque toda IA possui juízo de mérito idêntico ao de um ser humano.", ok:false},
    {t:"Porque essa frase não tem relação nenhuma com questões éticas.", ok:false}],
  explicacao:"A ausência de juízo de mérito reforça por que a supervisão e o senso crítico humanos continuam necessários." },
{ id:"b3-16", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Comparando os cinco critérios estudados (resolução de problemas, aprendizado, criatividade, emoção e adaptação), qual padrão se repete a favor da Inteligência Humana na maioria deles?",
  alternativas:[
    {t:"A flexibilidade construída por experiência, cultura e vivência pessoal — algo ao qual a IA não tem acesso.", ok:true},
    {t:"A velocidade de processamento de grandes volumes de dados.", ok:false},
    {t:"A capacidade de repetir exatamente o mesmo padrão, sem nenhuma variação.", ok:false},
    {t:"A ausência total de erros em qualquer contexto.", ok:false}],
  explicacao:"Em quase todos os critérios, a vantagem humana vem da experiência vivida — que a IA não possui." },
{ id:"b3-17", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Uma IA que gera imagens produz uma ilustração que reforça um estereótipo presente nos dados de treinamento. Qual é a causa mais provável?",
  alternativas:[
    {t:"O conjunto de dados de treinamento continha esse estereótipo, e o modelo aprendeu e reproduziu esse padrão.", ok:true},
    {t:"A IA decidiu, de forma consciente, criar aquele estereótipo por conta própria.", ok:false},
    {t:"Modelos de geração de imagem nunca podem produzir conteúdo problemático.", ok:false},
    {t:"O erro só pode ter sido causado por uma falha na conexão de internet.", ok:false}],
  explicacao:"A IA reflete os padrões — inclusive os problemáticos — presentes nos dados usados no treinamento." },
{ id:"b3-18", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que 'assumir a autoria do texto final, reescrevendo com as próprias palavras' é um dos combinados mais importantes de uso responsável de IA nos estudos?",
  alternativas:[
    {t:"Porque preserva o processo de aprendizagem e a responsabilidade pessoal sobre o conteúdo entregue, mesmo usando a IA como apoio.", ok:true},
    {t:"Porque reescrever automaticamente torna qualquer informação verdadeira.", ok:false},
    {t:"Porque a legislação proíbe qualquer uso de IA em atividades escolares.", ok:false},
    {t:"Porque reescrever é apenas mais rápido do que copiar o texto original.", ok:false}],
  explicacao:"A reescrita com as próprias palavras exige compreensão real do conteúdo — é isso que garante o aprendizado." },
{ id:"b3-19", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Um modelo de análise de dados detecta um padrão de fraude inédito em transações financeiras. Isso significa que ele teve uma 'ideia criativa', no mesmo sentido da criatividade humana?",
  alternativas:[
    {t:"Não — ele identificou uma anomalia estatística dentro de padrões aprendidos, o que é diferente da criatividade intencional humana.", ok:true},
    {t:"Sim — identificar qualquer padrão novo é sempre um ato de criatividade idêntico ao humano.", ok:false},
    {t:"Sim — sistemas de análise de dados têm consciência plena das próprias descobertas.", ok:false},
    {t:"Não é possível uma IA detectar nenhum padrão que seja novo.", ok:false}],
  explicacao:"Detecção estatística de padrões é diferente de criatividade, que envolve intenção, cultura e vivência." },
{ id:"b3-20", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Considerando todo o conteúdo estudado, por que a conclusão final defende 'tecnologia E raciocínio humano', em vez de escolher apenas um dos dois?",
  alternativas:[
    {t:"Porque a IA é poderosa, mas limitada pelos dados e pela ausência de juízo de mérito; decisões seguras exigem também o senso crítico humano.", ok:true},
    {t:"Porque a tecnologia é sempre perigosa e deveria ser evitada ao máximo.", ok:false},
    {t:"Porque o raciocínio humano se tornou desnecessário depois da criação da IA.", ok:false},
    {t:"Porque as duas coisas são exatamente iguais, e a escolha não faz diferença nenhuma.", ok:false}],
  explicacao:"É a síntese do capítulo: a IA amplia capacidades, mas a responsabilidade final continua sendo humana." }

];
BANCOS["3º A"] = { categorias:[], questoes: BANCO_3A };
