/* ============================================================
   BANCO DE QUESTÕES — Cultura Digital e Fundamentos de IA
   Turma: 1º Agronegócio EM Int 1
   60 questões (20 fáceis, 20 médias, 20 difíceis) — tipo "mc"
   Conteúdo: uso ético da IA, mitos e verdades, IH x IA,
   arquitetura (LLM/rede neural/aprendizado de máquina),
   processo de aprendizado de máquina, tokens e limites.
   ============================================================ */
const BANCO_AGRO = [

/* ---------------------------------------------------------- NÍVEL 1 (fácil) */
{ id:"a1-01", nivel:1, tipo:"mc", leitura:14, decay:25,
  enunciado:"Marcelo pediu para a IA escrever um resumo pronto sobre a Revolução Francesa em vez de estudar o assunto. O que ele fez, na prática?",
  alternativas:[
    {t:"Terceirizou o próprio aprendizado, recebendo o resultado sem produzir o raciocínio.", ok:true},
    {t:"Usou a IA apenas para revisar um texto que ele mesmo tinha escrito.", ok:false},
    {t:"Pediu à IA para explicar o conteúdo até ele entender sozinho.", ok:false},
    {t:"Usou a IA só para conferir datas históricas.", ok:false}],
  explicacao:"A IA entregou o texto pronto; não houve produção nem compreensão do conteúdo por parte do aluno." },
{ id:"a1-02", nivel:1, tipo:"mc", leitura:12, decay:25,
  enunciado:"A professora do Marcelo desconfiou do trabalho entregue mesmo estando tecnicamente perfeito. Por quê?",
  alternativas:[
    {t:"Porque faltava o estilo pessoal de escrita que ela já conhecia do aluno.", ok:true},
    {t:"Porque havia muitos erros de ortografia no texto.", ok:false},
    {t:"Porque o texto tinha menos de uma página.", ok:false},
    {t:"Porque o texto veio sem título.", ok:false}],
  explicacao:"A escrita carrega uma marca pessoal — e foi justamente essa marca que sumiu no texto gerado pela IA." },
{ id:"a1-03", nivel:1, tipo:"mc", leitura:12, decay:22,
  enunciado:"É correto afirmar que a Inteligência Artificial atual pensa e sente como um ser humano?",
  alternativas:[
    {t:"Não — ela processa padrões e dados, mas não tem consciência nem sentimentos.", ok:true},
    {t:"Sim — ela sente empatia real quando percebe tristeza em alguém.", ok:false},
    {t:"Sim — ela toma decisões éticas de forma totalmente independente.", ok:false},
    {t:"Sim — quanto mais moderna, mais parecida com a consciência humana ela fica.", ok:false}],
  explicacao:"É um dos mitos mais comuns: a IA reconhece padrões, mas não tem consciência nem empatia genuína." },
{ id:"a1-04", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"Por que a Inteligência Artificial pode errar ou repetir preconceitos em suas respostas?",
  alternativas:[
    {t:"Porque ela aprende a partir de dados, e dados falhos, incompletos ou enviesados geram respostas com os mesmos problemas.", ok:true},
    {t:"Porque a IA se cansa depois de muitas perguntas seguidas.", ok:false},
    {t:"Porque a internet fica lenta durante o uso.", ok:false},
    {t:"Porque ela é programada para errar de vez em quando.", ok:false}],
  explicacao:"A qualidade da resposta depende diretamente da qualidade dos dados usados no treinamento." },
{ id:"a1-05", nivel:1, tipo:"mc", leitura:12, decay:20,
  enunciado:"O que significa a sigla LLM?",
  alternativas:[
    {t:"Large Language Model — Grande Modelo de Linguagem.", ok:true},
    {t:"Live Learning Machine — Máquina de Aprendizado ao Vivo.", ok:false},
    {t:"Logical Learning Method — Método de Aprendizado Lógico.", ok:false},
    {t:"Local Language Memory — Memória Local de Linguagem.", ok:false}],
  explicacao:"LLM é o programa de IA treinado com milhões de textos para entender e gerar linguagem humana." },
{ id:"a1-06", nivel:1, tipo:"mc", leitura:12, decay:20,
  enunciado:"O que é a rede neural dentro da arquitetura de uma IA?",
  alternativas:[
    {t:"Uma estrutura inspirada no cérebro humano que ajuda a processar informações complexas.", ok:true},
    {t:"Um cabo físico que liga o computador à internet.", ok:false},
    {t:"Uma lista de perguntas frequentes programadas manualmente.", ok:false},
    {t:"Um tipo de vírus de computador.", ok:false}],
  explicacao:"Quanto mais complexa a rede neural, melhores tendem a ser as respostas da IA." },
{ id:"a1-07", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"O que é o Aprendizado de Máquina (Machine Learning)?",
  alternativas:[
    {t:"A técnica que permite à IA melhorar sozinha, analisando exemplos e ajustando suas respostas.", ok:true},
    {t:"Um curso obrigatório para quem quer trabalhar com computadores.", ok:false},
    {t:"O nome do teclado usado para programar IA.", ok:false},
    {t:"Um tipo de rede social para robôs.", ok:false}],
  explicacao:"É como ensinar uma criança a reconhecer gatos: quanto mais exemplos ela vê, melhor identifica o próximo." },
{ id:"a1-08", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"Qual é a primeira fase do processo de Aprendizado de Máquina?",
  alternativas:[
    {t:"A coleta de dados.", ok:true},
    {t:"O ajuste de parâmetros.", ok:false},
    {t:"A geração de imagens.", ok:false},
    {t:"A entrega do resultado final ao usuário.", ok:false}],
  explicacao:"Sem dados relevantes e variados coletados primeiro, não há o que treinar." },
{ id:"a1-09", nivel:1, tipo:"mc", leitura:12, decay:20,
  enunciado:"O que é um token, na linguagem de treinamento de IA?",
  alternativas:[
    {t:"A unidade básica de texto processada pelo modelo — uma palavra, parte dela ou um caractere.", ok:true},
    {t:"Cada pergunta feita pelo usuário ao chatbot.", ok:false},
    {t:"Um arquivo de vídeo usado no treinamento.", ok:false},
    {t:"A senha de acesso a uma ferramenta de IA.", ok:false}],
  explicacao:"É assim que se mede o volume de dados de treinamento: em bilhões ou trilhões de tokens." },
{ id:"a1-10", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"Assistentes de voz e chatbots simples são inteligentes de que forma?",
  alternativas:[
    {t:"Apenas dentro de um contexto limitado, seguindo roteiros programados para perguntas frequentes.", ok:true},
    {t:"São capazes de resolver qualquer assunto, sem limitação nenhuma.", ok:false},
    {t:"Aprendem sozinhos sem depender de nenhum tipo de programação.", ok:false},
    {t:"Têm total consciência do que estão dizendo.", ok:false}],
  explicacao:"Funcionam bem no contexto para o qual foram programados — e só nele." },
{ id:"a1-11", nivel:1, tipo:"mc", leitura:12, decay:20,
  enunciado:"Como a Inteligência Humana costuma aprender?",
  alternativas:[
    {t:"Por experiência, emoção e convívio social — observando, errando, acertando e debatendo.", ok:true},
    {t:"Somente lendo manuais técnicos.", ok:false},
    {t:"Somente repetindo padrões de dados.", ok:false},
    {t:"De forma idêntica à Inteligência Artificial.", ok:false}],
  explicacao:"A aprendizagem humana envolve intuição, cultura e interação social — algo que a IA não possui." },
{ id:"a1-12", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"Qual tipo de modelo de IA é treinado com foco em um setor específico, como medicina ou direito?",
  alternativas:[
    {t:"Modelo especializado.", ok:true},
    {t:"Modelo genérico.", ok:false},
    {t:"Modelo de geração de imagens.", ok:false},
    {t:"Modelo de rede social.", ok:false}],
  explicacao:"O modelo especializado busca informações precisas dentro de uma área específica de conhecimento." },
{ id:"a1-13", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"Qual tipo de modelo de IA é usado para criar imagens, vídeos e músicas?",
  alternativas:[
    {t:"Modelo de geração de conteúdo visual ou multimídia.", ok:true},
    {t:"Modelo de compreensão e análise de dados.", ok:false},
    {t:"Modelo especializado em direito.", ok:false},
    {t:"Modelo genérico de texto.", ok:false}],
  explicacao:"Esse tipo de modelo é usado em publicidade, entretenimento e arte." },
{ id:"a1-14", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"Um banco quer identificar transações suspeitas entre milhões de operações por dia. Que tipo de modelo de IA atende melhor essa necessidade?",
  alternativas:[
    {t:"Modelo de compreensão e análise de dados.", ok:true},
    {t:"Modelo de geração de conteúdo multimídia.", ok:false},
    {t:"Modelo genérico de conversação.", ok:false},
    {t:"Modelo especializado em medicina.", ok:false}],
  explicacao:"Esse tipo de modelo interpreta grandes volumes de dados, identifica tendências e detecta fraudes." },
{ id:"a1-15", nivel:1, tipo:"mc", leitura:12, decay:20,
  enunciado:"O que caracteriza um uso ÉTICO da IA nos estudos?",
  alternativas:[
    {t:"Usar a IA para entender o conteúdo, verificar as informações em fontes confiáveis e escrever com as próprias palavras.", ok:true},
    {t:"Copiar e colar a resposta da IA direto no trabalho, sem revisar nada.", ok:false},
    {t:"Confiar em qualquer resposta só porque o texto parece bem escrito.", ok:false},
    {t:"Nunca informar que a IA foi usada em algum momento do trabalho.", ok:false}],
  explicacao:"Uso ético: a IA sugere, você verifica e assume a responsabilidade pelo que entrega." },
{ id:"a1-16", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"Quais são os principais riscos apontados pelo uso da Inteligência Artificial na sociedade?",
  alternativas:[
    {t:"Privacidade individual, mudanças no mercado de trabalho e ética nas interações digitais.", ok:true},
    {t:"Apenas o preço alto das ferramentas de IA.", ok:false},
    {t:"Apenas a lentidão da internet ao usar IA.", ok:false},
    {t:"Nenhum risco relevante é apontado.", ok:false}],
  explicacao:"São desafios que precisam ser enfrentados de forma consciente, junto com as vantagens da IA." },
{ id:"a1-17", nivel:1, tipo:"mc", leitura:12, decay:20,
  enunciado:"Aproximadamente quantos tokens foram usados para treinar as IAs mais populares do mundo, segundo o material estudado?",
  alternativas:[
    {t:"Entre 100 e 300 bilhões de tokens.", ok:true},
    {t:"Cerca de 100 tokens.", ok:false},
    {t:"Cerca de 1 milhão de tokens.", ok:false},
    {t:"Um número que nunca foi medido.", ok:false}],
  explicacao:"O treinamento de LLMs envolve uma escala gigantesca de dados, medida em bilhões ou trilhões de tokens." },
{ id:"a1-18", nivel:1, tipo:"mc", leitura:12, decay:20,
  enunciado:"Se os dados usados para treinar uma IA forem incompletos, o que tende a acontecer com as respostas dela?",
  alternativas:[
    {t:"As respostas podem ficar imprecisas ou repetir os mesmos problemas dos dados.", ok:true},
    {t:"As respostas ficam automaticamente mais confiáveis.", ok:false},
    {t:"A IA para de funcionar completamente.", ok:false},
    {t:"Nada muda: a IA sempre acerta, independente dos dados.", ok:false}],
  explicacao:"A qualidade da resposta está diretamente ligada à qualidade e integridade dos dados de treino." },
{ id:"a1-19", nivel:1, tipo:"mc", leitura:12, decay:20,
  enunciado:"A Inteligência Artificial vai eliminar completamente o trabalho humano, segundo o material estudado?",
  alternativas:[
    {t:"Não — ela substitui tarefas repetitivas, mas também cria novas funções, exigindo adaptação.", ok:true},
    {t:"Sim — em poucos anos não haverá mais nenhum emprego humano.", ok:false},
    {t:"Sim — a IA já substituiu 100% dos trabalhos existentes.", ok:false},
    {t:"O material não trata desse assunto.", ok:false}],
  explicacao:"A IA muda a forma de trabalhar (cria funções como especialista em dados), mas não elimina o trabalho humano." },
{ id:"a1-20", nivel:1, tipo:"mc", leitura:13, decay:22,
  enunciado:"O que a Inteligência Artificial faz quando 'percebe' que um texto parece triste?",
  alternativas:[
    {t:"Reconhece padrões em palavras e expressões, como um detector — sem sentir empatia de verdade.", ok:true},
    {t:"Sente tristeza genuína, como um ser humano sentiria.", ok:false},
    {t:"Ignora completamente o conteúdo emocional do texto.", ok:false},
    {t:"Chama automaticamente um profissional humano para ajudar.", ok:false}],
  explicacao:"Perceber não é sentir: a IA identifica padrões, mas não tem empatia nem compaixão." },

/* ---------------------------------------------------------- NÍVEL 2 (médio) */
{ id:"a2-01", nivel:2, tipo:"mc", leitura:22, decay:35,
  texto:"Depois de terceirizar o resumo para a IA, Marcelo e Larissa resolveram testar a ferramenta a fundo, pedindo poemas, redações e piadas. O resultado vinha sempre rápido e tecnicamente correto.",
  enunciado:"Qual foi a dúvida levantada por Larissa durante esse teste?",
  alternativas:[
    {t:"Se estavam realmente aprendendo algo, ou apenas recebendo resultados prontos sem esforço próprio.", ok:true},
    {t:"Se a IA cobrava algum valor para responder tantas perguntas.", ok:false},
    {t:"Se o computador deles tinha memória suficiente para rodar a IA.", ok:false},
    {t:"Se a IA conseguiria repetir a mesma resposta duas vezes seguidas.", ok:false}],
  explicacao:"A qualidade técnica do texto não garante que houve aprendizagem — essa é a virada do capítulo." },
{ id:"a2-02", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Qual das opções abaixo é considerada um uso COERENTE e ético da Inteligência Artificial nos estudos?",
  alternativas:[
    {t:"Pedir à IA exemplos e ideias, conferir as informações e citar de onde vieram.", ok:true},
    {t:"Entregar como seu um texto integralmente gerado pela IA, sem nenhuma alteração.", ok:false},
    {t:"Confiar cegamente no que a IA escreveu só porque o texto parece bem elaborado.", ok:false},
    {t:"Pedir à IA para inventar uma fonte, caso não encontre uma real.", ok:false}],
  explicacao:"A IA funciona como apoio ao estudo; a verificação e a autoria continuam sendo responsabilidade da pessoa." },
{ id:"a2-03", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Por que dizer que 'a IA nunca erra, logo é mais confiável que qualquer pessoa' é considerado um mito?",
  alternativas:[
    {t:"Porque ela aprende com dados que podem conter erros ou vieses, e por isso precisa de supervisão humana constante.", ok:true},
    {t:"Porque, na verdade, a IA nunca comete erro nenhum.", ok:false},
    {t:"Porque as pessoas são sempre mais rápidas do que qualquer sistema de IA.", ok:false},
    {t:"Porque a IA só funciona quando está desconectada da internet.", ok:false}],
  explicacao:"Erros e vieses dos dados de treinamento se refletem diretamente nas respostas da IA." },
{ id:"a2-04", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Qual frase resume melhor a diferença entre a Inteligência Artificial da ficção científica e a IA real?",
  alternativas:[
    {t:"A IA real é uma ferramenta potente que processa dados e padrões; sentimentos e consciência continuam sendo ficção.", ok:true},
    {t:"A IA real já sente e decide sozinha; a ficção apenas exagera a aparência dos robôs.", ok:false},
    {t:"A IA real e a da ficção são idênticas, só muda a velocidade de processamento.", ok:false},
    {t:"A IA da ficção é mais lenta do que a IA real em todos os aspectos.", ok:false}],
  explicacao:"Potência computacional é real; consciência e emoção seguem sendo apenas ficção." },
{ id:"a2-05", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Uma característica descreve: 'resolve um problema de um jeito que ninguém tinha tentado antes, combinando experiências, cultura e intuição'. A qual tipo de inteligência isso se refere?",
  alternativas:[
    {t:"Inteligência Humana (IH).", ok:true},
    {t:"Inteligência Artificial (IA).", ok:false},
    {t:"Nenhuma das duas — isso não é possível.", ok:false},
    {t:"Apenas a IA especializada em criatividade.", ok:false}],
  explicacao:"Criatividade genuína, que combina experiência de vida e intuição, é uma marca da inteligência humana." },
{ id:"a2-06", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Uma característica descreve: 'analisa milhares de exemplos por segundo em busca de padrões'. A qual tipo de inteligência isso se refere?",
  alternativas:[
    {t:"Inteligência Artificial (IA).", ok:true},
    {t:"Inteligência Humana (IH).", ok:false},
    {t:"Nenhuma das duas.", ok:false},
    {t:"Apenas a inteligência emocional.", ok:false}],
  explicacao:"Velocidade e escala de processamento são a força característica da máquina." },
{ id:"a2-07", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Por que a IA precisa ser reprogramada ou receber novos dados para mudar de abordagem, diferente do ser humano?",
  alternativas:[
    {t:"Porque ela só é adaptável dentro dos limites do que já foi ensinado a ela.", ok:true},
    {t:"Porque ela se recusa a aprender qualquer coisa nova.", ok:false},
    {t:"Porque isso não é verdade: a IA se atualiza sozinha, sem nenhuma programação.", ok:false},
    {t:"Porque a IA tem memória infinita e nunca precisa de ajustes.", ok:false}],
  explicacao:"A flexibilidade humana vem da experiência vivida; a IA só muda dentro do que os dados permitem." },
{ id:"a2-08", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Um hospital quer um assistente digital que consulte protocolos médicos e literatura da área com precisão. Qual tipo de modelo de IA atende melhor essa necessidade?",
  alternativas:[
    {t:"Modelo especializado, treinado com foco no setor da saúde.", ok:true},
    {t:"Modelo de geração de conteúdo multimídia.", ok:false},
    {t:"Modelo genérico de conversação.", ok:false},
    {t:"Modelo de compreensão e análise de dados financeiros.", ok:false}],
  explicacao:"Modelos especializados são treinados com foco em um setor para buscar informações precisas." },
{ id:"a2-09", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Depois que o algoritmo analisa milhares de imagens de gatos procurando formatos e cores em comum, qual é a próxima etapa do Aprendizado de Máquina?",
  alternativas:[
    {t:"Comparar o resultado com o esperado e ajustar os parâmetros internos.", ok:true},
    {t:"Apagar todas as imagens usadas no treinamento.", ok:false},
    {t:"Encerrar o processo, já que a coleta de dados é a última etapa.", ok:false},
    {t:"Enviar as imagens para outro programa de edição.", ok:false}],
  explicacao:"O ciclo é: coleta → análise de padrões → ajuste de parâmetros, repetido até generalizar bem." },
{ id:"a2-10", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Por que a frase 'quanto mais dados, melhor' não é uma regra totalmente sem custo?",
  alternativas:[
    {t:"Porque mais dados aumentam o tempo e o custo computacional do treinamento.", ok:true},
    {t:"Porque a IA esquece os dados antigos assim que recebe dados novos.", ok:false},
    {t:"Porque dados demais impedem a IA de reconhecer qualquer padrão.", ok:false},
    {t:"Porque não existe limite de dados que uma IA pode processar.", ok:false}],
  explicacao:"Mais dados relevantes ajudam a IA a aprender melhor, mas custam tempo e recursos computacionais." },
{ id:"a2-11", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Uma agência de publicidade precisa gerar imagens originais para uma campanha. Qual tipo de modelo de IA é mais indicado?",
  alternativas:[
    {t:"Modelo de geração de conteúdo visual ou multimídia.", ok:true},
    {t:"Modelo especializado em direito.", ok:false},
    {t:"Modelo de compreensão e análise de dados.", ok:false},
    {t:"Modelo genérico apenas de texto.", ok:false}],
  explicacao:"A geração de imagens, vídeos e músicas é a função do modelo multimídia." },
{ id:"a2-12", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"O que está por trás quando uma pessoa conversa em português com um chatbot e recebe respostas coerentes?",
  alternativas:[
    {t:"Um LLM (Modelo de Linguagem), que compreende e produz texto.", ok:true},
    {t:"Apenas a rede neural, sem nenhum modelo de linguagem envolvido.", ok:false},
    {t:"Um banco de dados de respostas prontas digitadas por uma pessoa em tempo real.", ok:false},
    {t:"Um tradutor automático simples, sem relação com IA.", ok:false}],
  explicacao:"O modelo de linguagem é a parte que compreende e gera o texto da conversa." },
{ id:"a2-13", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Qual é a conclusão do capítulo sobre a comparação entre Inteligência Humana e Inteligência Artificial?",
  alternativas:[
    {t:"O melhor caminho é combinar a eficiência da IA com a profundidade e a empatia humanas.", ok:true},
    {t:"A IA vai superar a inteligência humana em todos os aspectos em pouco tempo.", ok:false},
    {t:"A IA deve ser evitada na escola, porque atrapalha o raciocínio dos alunos.", ok:false},
    {t:"A Inteligência Humana está ultrapassada e será substituída por completo.", ok:false}],
  explicacao:"A proposta é trabalhar em conjunto, cada tipo de inteligência na função em que é mais forte." },
{ id:"a2-14", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Por que 'mudar de opinião depois de ouvir um bom argumento em um debate' é um exemplo de Inteligência Humana, e não Artificial?",
  alternativas:[
    {t:"Porque mostra flexibilidade real: a pessoa se transforma ao longo do tempo por experiência própria.", ok:true},
    {t:"Porque a IA nunca recebe argumentos de ninguém.", ok:false},
    {t:"Porque debater é uma atividade exclusivamente de máquinas.", ok:false},
    {t:"Porque isso não tem relação nenhuma com inteligência.", ok:false}],
  explicacao:"A IA muda de resposta só quando reprogramada ou com novos dados; o ser humano muda por reflexão própria." },
{ id:"a2-15", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Um sistema reconhece uma expressão facial triste numa foto e responde com uma mensagem de apoio programada. Isso significa que a IA sentiu empatia?",
  alternativas:[
    {t:"Não — é uma simulação de resposta emocional, sem sentimento real por trás.", ok:true},
    {t:"Sim — toda IA moderna sente emoções reais.", ok:false},
    {t:"Sim — reconhecer uma expressão é o mesmo que sentir a emoção.", ok:false},
    {t:"Não é possível a IA reconhecer nenhum tipo de expressão facial.", ok:false}],
  explicacao:"A IA identifica padrões visuais e responde de forma programada — não há sentimento envolvido." },
{ id:"a2-16", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Qual é a diferença entre como a IH e a IA resolvem problemas complexos, segundo o capítulo?",
  alternativas:[
    {t:"A IH considera dados, emoções e intuição; a IA segue regras e padrões dentro dos limites dos dados recebidos.", ok:true},
    {t:"Ambas resolvem problemas exatamente da mesma forma, sem diferença alguma.", ok:false},
    {t:"A IA sempre demora mais para resolver problemas do que a IH.", ok:false},
    {t:"A IH depende só de regras matemáticas fixas, como a IA.", ok:false}],
  explicacao:"A flexibilidade da IH vem da bagagem emocional e cultural; a IA é limitada pelos dados que recebeu." },
{ id:"a2-17", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"O texto entregue por uma IA pode ser tecnicamente correto e ainda assim ser considerado um problema de aprendizagem. Por quê?",
  alternativas:[
    {t:"Porque a correção técnica não garante que a pessoa realmente entendeu ou produziu o conteúdo.", ok:true},
    {t:"Porque textos corretos são sempre proibidos nas escolas.", ok:false},
    {t:"Porque a IA nunca produz textos tecnicamente corretos.", ok:false},
    {t:"Porque só textos com erros de português têm valor pedagógico.", ok:false}],
  explicacao:"O problema não é a qualidade do texto, e sim a ausência do processo de aprendizagem por trás dele." },
{ id:"a2-18", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Como o Aprendizado de Máquina lida com o reconhecimento de imagens de gatos, segundo o exemplo do capítulo?",
  alternativas:[
    {t:"Analisa milhares de fotos, identifica padrões de formato e cor, e generaliza para reconhecer gatos nunca vistos antes.", ok:true},
    {t:"Memoriza cada foto individualmente e nunca reconhece uma imagem nova.", ok:false},
    {t:"Pergunta a uma pessoa qual é o animal antes de cada resposta.", ok:false},
    {t:"Usa apenas uma única imagem de referência para sempre.", ok:false}],
  explicacao:"É o processo de generalização: aprender com muitos exemplos para reconhecer casos novos." },
{ id:"a2-19", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Por que checar a informação em pelo menos duas fontes confiáveis é uma prática recomendada ao usar IA?",
  alternativas:[
    {t:"Porque a IA pode gerar respostas com dados incompletos, desatualizados ou tendenciosos.", ok:true},
    {t:"Porque a IA sempre erra de propósito para testar o usuário.", ok:false},
    {t:"Porque duas fontes sempre concordam entre si automaticamente.", ok:false},
    {t:"Porque isso é uma exigência apenas de trabalhos de faculdade.", ok:false}],
  explicacao:"Verificar fontes reduz o risco de espalhar informações falsas ou enviesadas geradas pela IA." },
{ id:"a2-20", nivel:2, tipo:"mc", leitura:24, decay:35,
  enunciado:"Qual é a função de um modelo de IA do tipo 'genérico'?",
  alternativas:[
    {t:"Entender e gerar textos variados, servindo a chatbots, tradutores e apoio à redação.", ok:true},
    {t:"Funcionar apenas dentro de hospitais e clínicas.", ok:false},
    {t:"Gerar exclusivamente imagens e vídeos publicitários.", ok:false},
    {t:"Detectar fraudes bancárias em tempo real.", ok:false}],
  explicacao:"O modelo genérico é versátil, aplicável em educação, atendimento e produção de conteúdo." },

/* ---------------------------------------------------------- NÍVEL 3 (difícil) */
{ id:"a3-01", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Se o aprendizado de máquina se baseia em tentativa, erro e ajuste, o que isso implica sobre confiar plenamente em qualquer resposta de uma IA?",
  alternativas:[
    {t:"Que não se deve confiar cegamente: mesmo generalizando bem, o modelo pode falhar em casos que fogem do padrão aprendido.", ok:true},
    {t:"Que toda resposta de IA está sempre 100% correta, sem exceção.", ok:false},
    {t:"Que o processo de tentativa e erro só acontece uma única vez, no início do treinamento.", ok:false},
    {t:"Que a IA para de errar assim que termina o treinamento.", ok:false}],
  explicacao:"O processo de tentativa e erro mostra que o modelo generaliza a partir de padrões — e padrões podem falhar em casos novos ou atípicos." },
{ id:"a3-02", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Um aluno usa a IA para gerar ideias, mas depois reescreve tudo com as próprias palavras, verifica as informações em fontes confiáveis e avisa que consultou a ferramenta. Por que essa conduta é considerada coerente com uso ético, mesmo usando IA amplamente?",
  alternativas:[
    {t:"Porque a autoria, a verificação e a transparência continuam sendo dele — a IA foi apoio, não substituição.", ok:true},
    {t:"Porque usar IA de qualquer forma já é sempre antiético, então não importa o cuidado tomado.", ok:false},
    {t:"Porque avisar que usou IA torna qualquer conduta automaticamente aceitável, mesmo sem verificar nada.", ok:false},
    {t:"Porque reescrever com outras palavras já garante 100% de precisão nas informações.", ok:false}],
  explicacao:"O uso ético não é 'usar ou não usar' a IA, mas manter a responsabilidade humana sobre verificação e autoria." },
{ id:"a3-03", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que dizer 'a IA vai roubar todos os empregos e nos tornar obsoletos' é tratado como mito, mesmo sendo verdade que a IA substitui tarefas repetitivas?",
  alternativas:[
    {t:"Porque a substituição de tarefas repetitivas coexiste com a criação de novas funções, exigindo adaptação em vez de eliminação total do trabalho.", ok:true},
    {t:"Porque a IA nunca substitui nenhuma tarefa em nenhuma situação.", ok:false},
    {t:"Porque empregos repetitivos não existem mais desde a criação da IA.", ok:false},
    {t:"Porque o mercado de trabalho nunca muda por causa de tecnologia.", ok:false}],
  explicacao:"O mito está no exagero da eliminação total; a realidade é transformação e adaptação do mercado." },
{ id:"a3-04", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que ter um cronômetro medindo o tempo de uma tarefa não é suficiente, sozinho, para definir se uma IA está tomando uma decisão 'como um esporte de marca' (por analogia) baseada apenas em números, sem julgamento?",
  alternativas:[
    {t:"Porque muitas decisões de IA dependem de padrões aprendidos e ponderações internas complexas, não apenas de uma métrica única e objetiva.", ok:true},
    {t:"Porque a IA nunca usa nenhum tipo de medição de tempo em seus processos.", ok:false},
    {t:"Porque só existe um único critério possível para qualquer IA, sempre.", ok:false},
    {t:"Porque cronômetros são proibidos em qualquer sistema de Inteligência Artificial.", ok:false}],
  explicacao:"O 'raciocínio' de uma IA combina múltiplos padrões aprendidos — não se resume a uma única variável simples." },
{ id:"a3-05", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Um sistema de IA especializado em diagnóstico médico é treinado majoritariamente com dados de uma única região do país. Qual risco isso cria, considerando o que se aprendeu sobre dados de treinamento?",
  alternativas:[
    {t:"O modelo pode generalizar mal para pacientes de outras regiões, repetindo o viés presente nos dados usados.", ok:true},
    {t:"Nenhum risco — modelos de IA sempre funcionam igualmente bem em qualquer população.", ok:false},
    {t:"O modelo perde automaticamente todos os dados anteriores.", ok:false},
    {t:"O risco existe só se o modelo for do tipo genérico, nunca no especializado.", ok:false}],
  explicacao:"Dados de treinamento pouco diversos tendem a gerar respostas enviesadas para grupos fora da amostra original." },
{ id:"a3-06", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que a criatividade humana é descrita como algo que 'combina experiências, cultura e intuição', enquanto a IA 'combina elementos já existentes sem intenção própria'?",
  alternativas:[
    {t:"Porque a IA gera conteúdo a partir de padrões aprendidos, sem propósito ou vivência pessoal por trás da escolha.", ok:true},
    {t:"Porque a IA nunca combina elementos de nenhuma forma.", ok:false},
    {t:"Porque a criatividade humana também segue regras fixas e programadas.", ok:false},
    {t:"Porque essa diferença não existe de fato — são processos idênticos.", ok:false}],
  explicacao:"Intenção, vivência e cultura são componentes exclusivamente humanos na criação; a IA reorganiza padrões." },
{ id:"a3-07", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Um modelo de IA responde de forma diferente a uma mesma pergunta feita em dois momentos distintos, meses depois de receber novos dados de treinamento. Isso mostra qual característica da IA?",
  alternativas:[
    {t:"A adaptação da IA depende de reprogramação ou de novos dados — não de reflexão própria como acontece na IH.", ok:true},
    {t:"Que a IA tem livre-arbítrio e decidiu mudar de opinião sozinha.", ok:false},
    {t:"Que o sistema está com defeito e precisa ser desligado.", ok:false},
    {t:"Que toda IA muda de resposta aleatoriamente, sem nenhum motivo.", ok:false}],
  explicacao:"A mudança de comportamento da IA vem de fora (novos dados/ajustes), não de uma decisão interna própria." },
{ id:"a3-08", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que o capítulo defende que o caminho ideal não é escolher entre IH OU IA, mas sim combinar as duas?",
  alternativas:[
    {t:"Porque a IA traz velocidade e escala no processamento, enquanto a IH contribui com julgamento ético, criatividade e empatia — cada uma complementa a limitação da outra.", ok:true},
    {t:"Porque a IA sempre erra e por isso precisa ser corrigida por humanos o tempo todo.", ok:false},
    {t:"Porque a IH é mais rápida que a IA em qualquer tarefa de cálculo.", ok:false},
    {t:"Porque não existe nenhuma diferença real entre as duas.", ok:false}],
  explicacao:"A força de uma cobre exatamente a fraqueza da outra: velocidade computacional x profundidade humana." },
{ id:"a3-09", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que treinar um modelo de IA com 'mais dados' melhora a eficácia, mas ao mesmo tempo cria um dilema prático para quem desenvolve a tecnologia?",
  alternativas:[
    {t:"Porque o ganho de qualidade custa mais tempo de processamento e mais recursos computacionais, gerando um trade-off entre desempenho e custo.", ok:true},
    {t:"Porque mais dados sempre pioram a qualidade das respostas, sem exceção.", ok:false},
    {t:"Porque não existe nenhum custo associado ao volume de dados usado.", ok:false},
    {t:"Porque dados extras são automaticamente descartados pelo sistema.", ok:false}],
  explicacao:"Há um equilíbrio entre volume de dados (que melhora o aprendizado) e o custo/tempo do treinamento." },
{ id:"a3-10", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Um estudante afirma: 'se a resposta da IA parece bem escrita e convincente, não preciso checar mais nada'. Qual é o principal risco dessa postura, segundo o material?",
  alternativas:[
    {t:"Escrita convincente não é garantia de veracidade — é justamente aí que mora o risco de espalhar informação falsa.", ok:true},
    {t:"Nenhum risco: texto bem escrito é sempre sinônimo de informação correta.", ok:false},
    {t:"O risco é apenas estético, sem relação com a veracidade do conteúdo.", ok:false},
    {t:"Esse risco só existe em textos muito curtos, nunca em textos longos.", ok:false}],
  explicacao:"A fluência do texto gerado por IA não tem relação direta com a exatidão factual do conteúdo." },
{ id:"a3-11", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que a escala de treinamento de uma IA é medida em tokens, e não simplesmente em 'número de textos' ou 'número de livros'?",
  alternativas:[
    {t:"Porque o token é uma unidade de processamento mais granular, permitindo medir com precisão o volume real de linguagem processada pelo modelo.", ok:true},
    {t:"Porque contar textos inteiros é tecnicamente impossível para qualquer sistema.", ok:false},
    {t:"Porque tokens e textos são exatamente a mesma coisa, apenas com nomes diferentes.", ok:false},
    {t:"Porque essa é apenas uma escolha estética dos desenvolvedores, sem função prática.", ok:false}],
  explicacao:"Como um token pode ser uma palavra, parte dela ou um caractere, ele oferece uma medida mais precisa e padronizada do que 'contar textos'." },
{ id:"a3-12", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Uma escola decide usar um modelo de IA genérico como assistente de dúvidas gerais dos alunos, mas percebe que ele erra questões técnicas específicas de uma disciplina profissionalizante. Qual é a explicação mais provável, considerando os tipos de LLM estudados?",
  alternativas:[
    {t:"Um modelo genérico não tem o mesmo nível de profundidade de um modelo especializado naquela área técnica específica.", ok:true},
    {t:"Modelos genéricos nunca cometem erros, então o problema deve ser da internet da escola.", ok:false},
    {t:"Todo modelo de IA é sempre especializado em todas as áreas ao mesmo tempo.", ok:false},
    {t:"O erro só pode ter sido causado por um vírus no computador.", ok:false}],
  explicacao:"Modelos genéricos são versáteis, mas modelos especializados são treinados com foco para dar precisão técnica numa área." },
{ id:"a3-13", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que a privacidade individual é apontada como um dos desafios do uso da Inteligência Artificial na sociedade?",
  alternativas:[
    {t:"Porque sistemas de IA frequentemente processam grandes volumes de dados pessoais para funcionar, o que levanta questões sobre como esses dados são usados e protegidos.", ok:true},
    {t:"Porque a IA nunca processa nenhum tipo de dado pessoal.", ok:false},
    {t:"Porque a privacidade só é um problema em jogos eletrônicos, não em IA.", ok:false},
    {t:"Porque esse tema não tem relação nenhuma com tecnologia.", ok:false}],
  explicacao:"O funcionamento de muitos sistemas de IA depende de dados — inclusive pessoais — o que exige cuidado ético e regulatório." },
{ id:"a3-14", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Um algoritmo de recomendação de conteúdo, treinado majoritariamente com as interações de um único grupo de usuários, passa a sugerir cada vez menos diversidade de conteúdo para todos. Que conceito do capítulo explica esse efeito?",
  alternativas:[
    {t:"O aprendizado a partir de dados enviesados ou pouco diversos, que a IA reproduz e amplifica em suas respostas.", ok:true},
    {t:"A IA decidiu, por conta própria, restringir a diversidade por questões éticas.", ok:false},
    {t:"Algoritmos de recomendação nunca são treinados com dados de usuários.", ok:false},
    {t:"Esse efeito é impossível de acontecer em qualquer sistema de IA.", ok:false}],
  explicacao:"Dados de treinamento enviesados tendem a se refletir — e até se intensificar — nas respostas geradas." },
{ id:"a3-15", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que dizer que a IA 'não tem juízo de mérito' é uma afirmação central para entender seus limites éticos?",
  alternativas:[
    {t:"Porque, sem consciência própria, ela não avalia se uma resposta é moralmente certa ou errada — apenas devolve o que o aprendizado sugere.", ok:true},
    {t:"Porque juízo de mérito é um conceito que só existe em tribunais, sem relação com IA.", ok:false},
    {t:"Porque toda IA possui juízo de mérito idêntico ao humano.", ok:false},
    {t:"Porque essa frase não tem nenhuma relação com ética.", ok:false}],
  explicacao:"A ausência de juízo de mérito reforça por que a supervisão e o senso crítico humanos continuam necessários." },
{ id:"a3-16", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Comparando os cinco critérios do capítulo (resolução de problemas, aprendizado, criatividade, emoção e adaptação), qual é o padrão que se repete em favor da Inteligência Humana em quase todos eles?",
  alternativas:[
    {t:"A flexibilidade construída por experiência, cultura e vivência pessoal, algo que a IA não tem acesso.", ok:true},
    {t:"A velocidade de processamento de grandes volumes de dados.", ok:false},
    {t:"A capacidade de repetir exatamente o mesmo padrão sem variação.", ok:false},
    {t:"A ausência total de erros em qualquer situação.", ok:false}],
  explicacao:"Em quase todos os critérios comparados, a vantagem humana vem da experiência vivida — algo que a IA não possui." },
{ id:"a3-17", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Um sistema de IA multimídia gera uma imagem que reproduz um estereótipo presente nos dados usados em seu treinamento. Qual é a causa raiz mais provável, segundo o capítulo?",
  alternativas:[
    {t:"O conjunto de dados de treinamento continha esse estereótipo, e o modelo aprendeu e reproduziu esse padrão.", ok:true},
    {t:"A IA decidiu, de forma consciente, criar aquele estereótipo por conta própria.", ok:false},
    {t:"Modelos multimídia nunca podem gerar conteúdo problemático.", ok:false},
    {t:"O erro só pode ter vindo de uma falha na internet do usuário.", ok:false}],
  explicacao:"A IA reflete os padrões (inclusive problemáticos) presentes nos dados com que foi treinada." },
{ id:"a3-18", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Por que 'assumir a autoria do texto final, reescrevendo com as próprias palavras' é considerado um dos combinados mais importantes de uso responsável de IA nos estudos?",
  alternativas:[
    {t:"Porque preserva o processo de aprendizagem e a responsabilidade pessoal sobre o conteúdo entregue, mesmo usando a IA como apoio.", ok:true},
    {t:"Porque reescrever automaticamente torna qualquer informação verdadeira, sem necessidade de checagem.", ok:false},
    {t:"Porque a lei proíbe qualquer uso de IA em atividades escolares.", ok:false},
    {t:"Porque reescrever é mais rápido do que simplesmente copiar o texto original.", ok:false}],
  explicacao:"A reescrita com as próprias palavras exige compreensão real do conteúdo — é isso que garante o aprendizado." },
{ id:"a3-19", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Um modelo de análise de dados detecta um padrão de fraude nunca visto antes em transações bancárias. Isso significa que ele teve uma 'ideia criativa', no mesmo sentido da criatividade humana?",
  alternativas:[
    {t:"Não — ele identificou uma anomalia estatística dentro de padrões aprendidos, o que é diferente da criatividade humana intencional.", ok:true},
    {t:"Sim — identificar qualquer padrão novo é sempre um ato de criatividade idêntico ao humano.", ok:false},
    {t:"Sim — porque toda IA de análise de dados tem consciência plena das próprias descobertas.", ok:false},
    {t:"Não é possível uma IA detectar nenhum padrão novo.", ok:false}],
  explicacao:"Detecção estatística de padrões é diferente de criatividade — que envolve intenção, cultura e vivência." },
{ id:"a3-20", nivel:3, tipo:"mc", leitura:28, decay:42,
  enunciado:"Considerando todo o capítulo, por que a conclusão final defende 'tecnologia E raciocínio humano', em vez de escolher apenas um dos dois?",
  alternativas:[
    {t:"Porque a IA é poderosa mas limitada pelos dados e pela ausência de juízo de mérito; decisões seguras exigem também o senso crítico humano.", ok:true},
    {t:"Porque a tecnologia é sempre perigosa e deve ser evitada ao máximo.", ok:false},
    {t:"Porque o raciocínio humano se tornou desnecessário depois da criação da IA.", ok:false},
    {t:"Porque as duas coisas são exatamente iguais e a escolha não faz diferença.", ok:false}],
  explicacao:"É a síntese do capítulo: a IA amplia capacidades, mas a responsabilidade e o julgamento final continuam sendo humanos." }

];
BANCOS["1º Agro"] = { categorias:[], questoes: BANCO_AGRO };
